// Register
POST http://localhost:3000/auth
Content-Type: application/json

{
  "username": "TAT11112",
  "password": "12345678",
  "studentID": "60167eceb72a5832ec7ffded"
}

###
// Register admin
POST http://localhost:3000/auth/admin
Content-Type: application/json

{
  "username": "admin123",
  "password": "admin123"
}

###
// Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "TTT1234",
  "password": "12345678"
}

###
POST http://localhost:3000/students/forgotpass
Content-Type: application/json

{
  "username": "TuanTran",
  "newpass": "21111111"
}
###

POST http://localhost:3000/students/create
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "student_name": "ABC",
  "phone_number": "23232232",
  "birthdate": "22-2",
  "address": "22323 HHT",
  "class_id": "5fdc576e24109624d024dcb0"
}
###

PUT http://localhost:3000/students/5fdae163d0e1181c64210143
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "name": "TTT123",
  "birthdate": "2/2",
  "phone_number": "1232131",
  "address": "123 ABC"
}
###

PUT http://localhost:3000/students/5fdae163d0e1181c64210
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "name": "TTT123",
  "birthdate": "2/2",
  "phone_number": "1232131",
  "address": "123 ABC"
}
###

PUT http://localhost:3000/test/6007dfb4d3e7e1
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "name": "TTT123",
  "birthdate": "2/2",
  "phone_number": "1232131",
  "address": "123 ABC"
}
###

POST http://localhost:3000/test/users
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "username": "TuanTranad",
  "password": "Tsadsadwq3231"
}

###
DELETE  http://localhost:3000/students/s
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

###
POST http://localhost:3000/students/create
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "student_name": "ABC",
  "phone_number": "2313123123",
  "birthdate": "21/3",
  "address": "22323 HHT",
  "class_id": "5fdc576e24109624d024dcb0"
}

###
POST http://localhost:3000/class/create
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "class_name": "Tin2312312",
  "phone_number": "sdsadasd"
}

###
// Update User
PUT http://localhost:3000/users/600a4d4c1235f3299804f5d4
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "student_name": "TTT123",
  "birthdate": "2/2",
  "phone_number": "1232131",
  "address": "123 D"
}

###
// Update Student
PUT http://localhost:3000/students/600a4d321235f3299804f5d2
Content-Type: application/json
Cookie: auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRlZDc1OWE3NDgzYjIyZTBjNzQ2OTAiLCJpYXQiOjE2MTA5NTI5NDF9.pmsiBug_kRRMFRYpojuiaypaszFIo53YLdA_cX82anQ

{
  "name": "JIN22",
  "birthdate": "23123213"
  
}